# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://andycroll.com
title: Andy Croll
author: Andy Croll
description: "CTO at CoverageBook, Rubyist, Conference Organizer, Speaker, Bootstrapper & Twin Dad."

base_url: ""
image_url: "https://images.andycroll.com"

include: ["_headers"]
exclude: ["scripts"]

email: andy@goodscary.com

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-tailwind

tailwind:
  input: assets/css/app.css
  minify: true

permalink: /:categories/:title/
